name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: |
        docker build -t hallo-welt .
        docker save hallo-welt:latest -o hallo-welt.tar
    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: hallo-welt-image
        path: hallo-welt.tar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Download Docker image artifact
      uses: actions/download-artifact@v2
      with:
        name: hallo-welt-image
    - name: Load docker image
      run: |
        docker load -i hallo-welt.tar
    - name: Run smoke test
      run: |
        echo "Running smoke test..."
        docker run hallo-welt:latest


  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging..."
        # Fügen Sie hier Ihre Staging-Deployment-Logik ein

    - name: QA Check
      run: |
        echo "Running QA checks..."
        # Hier könnten automatisierte QA-Skripte laufen

    - name: Deploy to production
      run: |
        echo "Deploying to production..."
        # Fügen Sie hier Ihre Produktions-Deployment-Logik ein
